-- AlterTable
ALTER TABLE `imo` ADD COLUMN `address` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `category` INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN `type` INTEGER NOT NULL DEFAULT 0,
    MODIFY `title` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `description` TEXT NOT NULL DEFAULT '',
    MODIFY `reference` VARCHAR(191) NOT NULL DEFAULT '',
    MODIFY `nb_piece` INTEGER NOT NULL DEFAULT 0,
    MODIFY `nb_room` INTEGER NOT NULL DEFAULT 0,
    MODIFY `surface` INTEGER NOT NULL DEFAULT 0,
    MODIFY `price` INTEGER NOT NULL DEFAULT 0;
